[plugin]
repository = "https://github.com/CMDRNuffin/BetterMountRoulette.git"
commit = "6899d5883386058aacc01755a37877ed9bb727f1"
version = "1.6.0.22"
owners = ["CMDRNuffin"]
changelog = """Update for 7.1/API 11"""
