[plugin]
repository = "https://github.com/CMDRNuffin/BetterMountRoulette.git"
commit = "49cd765517747aa750b4668c45cf5c1639a7cb56"
version = "1.2.0.13"
owners = ["CMDRNuffin"]
changelog = """Upgrade to Dalamud API 9"""
