[plugin]
repository = "https://github.com/CMDRNuffin/BetterMountRoulette.git"
commit = "5975309d6db1db8f2387b4fa8590f0a003786693"
version = "1.7.3.28"
owners = ["CMDRNuffin"]
changelog = """Update for 7.3

Also adds an option to override mount group size settings for frontline/rival wings."""
