[plugin]
repository = "https://github.com/CMDRNuffin/BetterMountRoulette.git"
commit = "508bb97b1c29286386dcd38636f7dbb0441cd2c0"
version = "1.5.0.18"
owners = ["CMDRNuffin"]
changelog = """Added flying mount roulette back to the game in all the usual places (action menu, mount guide)."""
