[plugin]
repository = "https://github.com/CMDRNuffin/BetterMountRoulette.git"
commit = "491501dc49fd857ae2ffb32aeb923475a809a162"
version = "1.7.2.27"
owners = ["CMDRNuffin"]
changelog = """Update for 7.3

Also adds an option to override mount group size settings for frontline/rival wings."""
