[plugin]
repository = "https://github.com/CMDRNuffin/BetterMountRoulette.git"
commit = "3039b7c76500d167da5e9a3116b0e08e5be21df8"
version = "1.5.0.19"
owners = ["CMDRNuffin"]
changelog = """Fix: Plugin would crash and burn if changing the mount guide's roulette buttons failed."""
